In [1]:
!pip install torch torchvision torchaudio

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import torch
x=torch.empty(5,3) # printing the 5,rows and 3 columns
print(x)

tensor([[1.4401e-27, 3.1978e-41, 0.0000e+00],
        [0.0000e+00, 4.4721e+21, 7.7701e+31],
        [4.8215e+30, 1.5414e-44, 7.7015e+31],
        [6.1268e+20, 4.6831e+30, 6.5861e-44],
        [6.3453e+28, 6.9790e+22, 2.8500e-41]])


In [ ]:
x=torch.empty(2,4,3)
print(x)

tensor([[[-2.3337e-38,  3.1973e-41, -2.8020e-38],
         [ 3.1973e-41,  1.0886e+27,  2.9602e+29],
         [ 1.7938e+25,  1.9205e+31,  7.1856e+22],
         [ 4.6114e+24,  1.2123e+25,  2.7946e+20]],

        [[ 1.8524e+28,  1.1692e-19,  1.1351e-43],
         [ 0.0000e+00, -1.9783e-35,  4.3168e-41],
         [-1.9783e-35,  4.3168e-41,  9.4357e+26],
         [ 4.8617e+30,  6.8664e-44,  0.0000e+00]]])


In [ ]:
x=torch.rand(5,3)
print(x)

tensor([[0.3442, 0.4339, 0.8052],
        [0.4303, 0.6602, 0.0696],
        [0.7311, 0.3647, 0.0379],
        [0.8104, 0.3814, 0.0491],
        [0.9117, 0.5528, 0.8338]])


In [ ]:
x=torch.zeros(2,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x.dtype

torch.float32

In [ ]:
#change the data type
x=x.type(torch.int)
print(x)

tensor([5, 3], dtype=torch.int32)


In [ ]:
x=x.type(torch.double)
print(x)

tensor([5., 3.], dtype=torch.float64)


In [ ]:
x=torch.rand(2,4)
y=torch.rand(2,4)
print(x)
print(y)
z=torch.add(x,y)
print(z)

tensor([[0.2202, 0.2311, 0.2718, 0.0816],
        [0.9185, 0.3225, 0.8479, 0.6587]])
tensor([[0.6044, 0.7847, 0.0755, 0.4308],
        [0.7713, 0.5169, 0.3907, 0.6008]])
tensor([[0.8246, 1.0158, 0.3472, 0.5124],
        [1.6898, 0.8394, 1.2386, 1.2595]])


In [ ]:
k=x+y
print(k)

tensor([[0.8246, 1.0158, 0.3472, 0.5124],
        [1.6898, 0.8394, 1.2386, 1.2595]])


In [ ]:
y.add_(x)
print(y)

tensor([[0.8246, 1.0158, 0.3472, 0.5124],
        [1.6898, 0.8394, 1.2386, 1.2595]])


In [ ]:
z=torch.sub(x,y)
print(z)

tensor([[-0.6044, -0.7847, -0.0755, -0.4308],
        [-0.7713, -0.5169, -0.3907, -0.6008]])


In [ ]:
m=torch.mul(x,y)
print(m)

tensor([[0.1816, 0.2347, 0.0944, 0.0418],
        [1.5522, 0.2707, 1.0502, 0.8296]])


In [ ]:
x=torch.rand(3,3)
print(x)

tensor([[0.9461, 0.9622, 0.4574],
        [0.8462, 0.4641, 0.7304],
        [0.5457, 0.3910, 0.3905]])


In [ ]:
print(x[0,0])
print(x[0,:]) # printing single row
print(x[:,0]) # printing first column

tensor(0.9461)
tensor([0.9461, 0.9622, 0.4574])
tensor([0.9461, 0.8462, 0.5457])


In [ ]:
print(x[1,1].item()) # printing values as item rather then tensors

0.4641389846801758


In [ ]:
y=x.view(9)
print(y) # printing all values of matrix in single tenor

tensor([0.9461, 0.9622, 0.4574, 0.8462, 0.4641, 0.7304, 0.5457, 0.3910, 0.3905])


In [ ]:
y=x.view(-1,3)
print(y)
y.size()

tensor([[0.9461, 0.9622, 0.4574],
        [0.8462, 0.4641, 0.7304],
        [0.5457, 0.3910, 0.3905]])


torch.Size([3, 3])

In [ ]:
import numpy as np
a=torch.ones(5)
print(a)
p=a.numpy()
print(p)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1) # boath are pointing same location
print(a)
print(p)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
b=torch.from_numpy(p)
print(b)

tensor([2., 2., 2., 2., 2.])


In [ ]:
a+=1
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])


In [ ]:
# running the tensor on GPU
if torch.cuda.is_available():
  device=torch.device("cuda")
  y=torch.ones_like(x,device=device)
  x=x.to(device)

In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
z=x+y
print(z)

tensor([[1.8921, 1.9243, 0.9148],
        [1.6925, 0.9283, 1.4608],
        [1.0914, 0.7821, 0.7809]])


In [ ]:
z.numpy()

array([[1.8921382 , 1.9243336 , 0.914832  ],
       [1.692457  , 0.92827797, 1.4608258 ],
       [1.0913719 , 0.7820715 , 0.7809342 ]], dtype=float32)

In [ ]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
a=a.to(device)
a=a+1
print(a)
print(b)

cpu
tensor([4., 4., 4., 4., 4.])
tensor([3., 3., 3., 3., 3.])


In [ ]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
# Autograds from pytorch
a=torch.randn(2,requires_grad=True)
print(a)

tensor([2.0053, 0.5199], requires_grad=True)


In [ ]:
y=a+2
print(y)

tensor([4.0053, 2.5199], grad_fn=<AddBackward0>)


In [ ]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([48.1271, 19.0504], grad_fn=<MulBackward0>) tensor(33.5887, grad_fn=<MeanBackward0>)


In [ ]:
out.backward()
print(a.grad)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
x=torch.randn(1,10,requires_grad=True)
prev_h=torch.randn(1,20 ,requires_grad=True)
w_h=torch.randn(20,20,requires_grad=True)
w_x=torch.randn(20,10,requires_grad=True)

In [ ]:
i2h=torch.mm(w_x,x.t())
h2h=torch.mm(w_h,prev_h.t())
next_h=torch.tanh(i2h+h2h)

In [ ]:
print(i2h.shape)
print(h2h.shape)
print(next_h.shape)

torch.Size([20, 1])
torch.Size([20, 1])
torch.Size([20, 1])


In [ ]:
loss=next_h.sum()
print(loss)

tensor(5.2178, grad_fn=<SumBackward0>)


In [ ]:
loss.backward()

# pytorch tensor


In [3]:
import torch
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
