In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

import pandas as pd
from tensorflow.keras.models import Sequential
from keras import layers
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding # Import Embedding from the correct location

In [ ]:
sent=['I love my dog',
      'I love my cat',
      'You love my dog!',
      'i am a good engineer',
      'i love my friend',
      'world is changing everyday',
      'i read books','what are you doing','find me the dog']

In [ ]:
sent

['I love my dog',
 'I love my cat',
 'You love my dog!',
 'i am a good engineer',
 'i love my friend',
 'world is changing everyday',
 'i read books',
 'what are you doing',
 'find me the dog']

In [ ]:
vocab_size=1000

In [ ]:
onehot_rep=[one_hot(words,vocab_size) for words in sent]
onehot_rep

[[895, 614, 599, 874],
 [895, 614, 599, 140],
 [161, 614, 599, 874],
 [895, 299, 727, 377, 361],
 [895, 614, 599, 452],
 [187, 448, 945, 467],
 [895, 183, 705],
 [455, 889, 161, 303],
 [127, 106, 371, 874]]

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_rep,padding='post',maxlen=sent_length)
print(embedded_docs)

[[895 614 599 874   0   0   0   0]
 [895 614 599 140   0   0   0   0]
 [161 614 599 874   0   0   0   0]
 [895 299 727 377 361   0   0   0]
 [895 614 599 452   0   0   0   0]
 [187 448 945 467   0   0   0   0]
 [895 183 705   0   0   0   0   0]
 [455 889 161 303   0   0   0   0]
 [127 106 371 874   0   0   0   0]]


In [ ]:
dim=7
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))

In [ ]:
model.compile('adam','mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 165ms/step
[[[-0.00513045  0.00242035 -0.03006123  0.00715914 -0.03221917
   -0.04312962 -0.02877475  0.03550443  0.00096841  0.00809325]
  [ 0.00261698  0.04341203  0.04932773  0.00084251  0.04450034
    0.02970917 -0.02040305 -0.04087251  0.04895588 -0.00892889]
  [ 0.04868123 -0.00387521 -0.02392036  0.03720274  0.01791878
    0.00822334 -0.00064424  0.00577811  0.04459916 -0.02039853]
  [-0.01476055 -0.03193729  0.01545656  0.0408395  -0.01969638
   -0.04067608  0.02644103  0.04217701 -0.00259423 -0.02514912]
  [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294
   -0.00658569 -0.00780385 -0.03900794  0.02414583 -0.01972724]
  [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294
   -0.00658569 -0.00780385 -0.03900794  0.02414583 -0.01972724]
  [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294
   -0.00658569 -0.00780385 -0.03900794  0.02414583 -0.01972724]
  [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.0084

In [ ]:
print(model.predict(embedded_docs)[7])

1/1 [==============================] - 0s 26ms/step
[[-0.04405326 -0.0021992   0.02837351  0.00338447  0.00553272 -0.03025049
   0.02136557  0.01842458  0.03475771  0.01611993]
 [-0.0192691   0.00451748  0.01701811 -0.01077078 -0.04730627 -0.04156744
   0.01989491  0.04980919  0.00900972 -0.00794971]
 [-0.03173164 -0.04705557 -0.03814346 -0.03492956 -0.00185999 -0.03962892
   0.04837164 -0.04836041 -0.04073361 -0.04419638]
 [-0.04622406 -0.04108533  0.01478512 -0.03399201  0.0247334   0.01809618
   0.03920367  0.01309237  0.00182308  0.01155763]
 [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294 -0.00658569
  -0.00780385 -0.03900794  0.02414583 -0.01972724]
 [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294 -0.00658569
  -0.00780385 -0.03900794  0.02414583 -0.01972724]
 [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294 -0.00658569
  -0.00780385 -0.03900794  0.02414583 -0.01972724]
 [ 0.02138485 -0.02865443  0.04895021 -0.01408303  0.00845294 -0.00658569

In [7]:
# hugging face embeddings
!pip install transformers torch
import transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification,AutoModel
import torch

In [8]:
def embeddings(text,model_name='sentence-transformers/all-MiniLM-L6-v2'):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)
    inputs=tokenizer(text,return_tensors='pt',truncation=True,padding=True)
    with torch.no_grad():
      outputs=model(**inputs)
      embeddings = outputs.last_hidden_state.mean(dim=1)
      return embeddings.numpy()





In [9]:
text = "Hello, how are you?"
embeddings = embeddings(text) # Call the correctly named function 'embeddings'
print(f"Embeddings shape: {embeddings.shape}")
print(f"Embeddings: {embeddings}")

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Embeddings shape: (1, 384)
Embeddings: [[ 9.96381864e-02  1.79823592e-01  4.78073031e-01  3.66090596e-01
  -1.56247795e-01 -4.39272434e-01  2.39034563e-01  2.58718543e-02
  -4.79457825e-01  9.07885432e-02 -4.59986404e-02 -3.45117040e-03
  -1.48997307e-01 -1.14523895e-01  2.87834942e-01 -2.60024101e-01
   4.68957901e-01 -4.64138240e-01 -5.86223841e-01  2.03487292e-01
  -3.44727248e-01  1.36152759e-01  1.90600559e-01  3.20307225e-01
  -2.98052073e-01 -2.85083711e-01  1.58433706e-01  1.68983415e-01
   6.59741163e-02 -5.51420391e-01 -3.04420620e-01  3.51294607e-01
  -2.12645933e-01  3.36000063e-02  2.97330953e-02  2.75763959e-01
  -2.07529485e-01 -6.18553102e-01  1.10412240e-02 -8.70956481e-02
   1.47855580e-01 -1.95334300e-01 -1.11506417e-01 -2.16398865e-01
   4.43344504e-01 -3.58415544e-01  1.28620982e-01  3.73929322e-01
   5.28519273e-01  2.42702868e-02 -5.24060905e-01 -1.77889109e-01
  -2.09619597e-01  1.92566335e-01  3.17258149e-01  2.16447458e-01
  -3.37274164e-01  2.12615095e-02  3.

In [10]:
#import pipelined
from transformers import pipeline
transcriber = pipeline(model="openai/whisper-large-v2")
transcriber("https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac")

config.json:   0%|          | 0.00/1.99k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/6.17G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/4.29k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/283k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/836k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.48M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/494k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/185k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `

{'text': ' I have a dream that one day this nation will rise up and live out the true meaning of its creed.'}

In [13]:
text=transcriber("https://huggingface.co/datasets/Narsil/asr_dummy/resolve/main/mlk.flac")
text

/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(


{'text': ' I have a dream that one day this nation will rise up and live out the true meaning of its creed.'}

In [14]:
# prompt: pass the audio files from temporary files in colab

from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

  # Assuming 'transcriber' is your pipeline for audio transcription
  try:
    text = transcriber(fn)  # Pass the uploaded filename to your transcriber
    print(f"Transcription of {fn}: {text}")
  except Exception as e:
    print(f"Error transcribing {fn}: {e}")


Saving sunshine.mp3 to sunshine (1).mp3
User uploaded file "sunshine (1).mp3" with length 2792834 bytes


/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(


Transcription of sunshine (1).mp3: {'text': " We are now at the area of Upper Session Road Night, dear, as I lay sleeping I dreamed I held you in my arms When I awoke, dear, I was mistaken So I hung my head and I cried You are my sunshine, my only sunshine You make me happy when skies are grey You'll never know dear, how much I love you Please don't take my sunshine away I'll always love you and make you happy And nothing else could come between But if you leave me to love another You'll have shattered all of my dreams You are my sunshine, my only sunshine You make me happy when skies are grey You'll never know dear, how much I love you Please don't take my sunshine away"}


In [16]:
!pip install sentence_transformers # Install the missing sentence_transformers library.

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.3/245.3 kB 8.2 MB/s eta 0:00:00


In [17]:
# simple similarity search of pdf using hugging face embeddings
import sentence_transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
import torch

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [18]:
# extracting the text from the pdf
!pip install PyPDF2
import PyPDF2
import os
# read read pdf from the link
doc = PyPDF2.PdfReader("Attention all you need.pdf")
# extract the text from the pdf
text = ""
for page in doc.pages:
    text += page.extract_text()
    print(text)

Streaming output truncated to the last 5000 lines.
illia.polosukhin@gmail.com
Abstract
The dominant sequence transduction models are based on complex recurrent or
convolutional neural networks that include an encoder and a decoder. The best
performing models also connect the encoder and decoder through an attention
mechanism. We propose a new simple network architecture, the Transformer,
based solely on attention mechanisms, dispensing with recurrence and convolutions
entirely. Experiments on two machine translation tasks show these models to
be superior in quality while being more parallelizable and requiring significantly
less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-
to-German translation task, improving over the existing best results, including
ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task,
our model establishes a new single-model state-of-the-art BLEU score of 41.8 after
training for 3.5 days on eight GPUs, a small fractio

In [19]:
# make the text into chunks of sentences
sentences = text.split('. ')
sentences


['Provided proper attribution is provided, Google hereby grants permission to\nreproduce the tables and figures in this paper solely for use in journalistic or\nscholarly works.\nAttention Is All You Need\nAshish Vaswani∗\nGoogle Brain\navaswani@google.comNoam Shazeer∗\nGoogle Brain\nnoam@google.comNiki Parmar∗\nGoogle Research\nnikip@google.comJakob Uszkoreit∗\nGoogle Research\nusz@google.com\nLlion Jones∗\nGoogle Research\nllion@google.comAidan N',
 'Gomez∗ †\nUniversity of Toronto\naidan@cs.toronto.eduŁukasz Kaiser∗\nGoogle Brain\nlukaszkaiser@google.com\nIllia Polosukhin∗ ‡\nillia.polosukhin@gmail.com\nAbstract\nThe dominant sequence transduction models are based on complex recurrent or\nconvolutional neural networks that include an encoder and a decoder',
 'The best\nperforming models also connect the encoder and decoder through an attention\nmechanism',
 'We propose a new simple network architecture, the Transformer,\nbased solely on attention mechanisms, dispensing with recurren

In [20]:
# prompt: define embeddings function and pass the sentence chunks into the embeddings

def embeddings(text, model_name='sentence-transformers/all-MiniLM-L6-v2'):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
        embeddings = outputs.last_hidden_state.mean(dim=1)
        return embeddings.numpy()

sentence_embeddings = [embeddings(sentence) for sentence in sentences]


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [21]:
sentence_embeddings[0]

array([[ 9.01108682e-02,  1.94376009e-03,  4.50636260e-03,
         5.26342392e-02, -4.16866504e-03, -3.12544629e-02,
        -4.50808033e-02,  1.51193077e-02, -5.58450706e-02,
         1.78590462e-01,  1.01582885e-01, -7.42673129e-02,
         2.75459737e-02,  2.70412974e-02, -9.62652490e-02,
         9.18884668e-03,  1.09495753e-02,  1.32605601e-02,
        -6.51333779e-02,  8.91672149e-02, -3.29462141e-02,
        -2.81094909e-02,  1.84700951e-01, -1.14805512e-01,
         1.32368073e-01, -4.17335667e-02, -6.49255738e-02,
        -7.55109042e-02,  4.30744775e-02, -3.01274266e-02,
        -5.15113771e-02,  7.54266307e-02,  1.63201969e-02,
         8.83455053e-02, -1.90007277e-02, -1.50283501e-02,
         8.96092504e-02,  4.67010066e-02,  7.59367794e-02,
         1.92025732e-02, -1.34252841e-02, -1.62585631e-01,
         3.09707299e-02, -3.05605233e-02,  3.42674181e-02,
         8.93798023e-02, -1.68107331e-01, -2.20835861e-02,
        -1.27372205e-01,  5.96865686e-03, -1.13250390e-0

In [22]:
query="Encoder and Decoder stacks"
query_embedding=embeddings(query)


/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [28]:
# prform similarity search
from sklearn.metrics.pairwise import cosine_similarity
import torch

# Convert query_embedding to a PyTorch tensor
query_embedding_tensor = torch.from_numpy(query_embedding)

# Convert sentence_embeddings to a PyTorch tensor
sentence_embeddings_tensor = torch.stack([torch.from_numpy(embedding) for embedding in sentence_embeddings])

# Calculate cosine similarity
similarities = torch.cosine_similarity(query_embedding_tensor, sentence_embeddings_tensor)

# Find the index of the most similar sentence
most_similar_index = torch.argmax(similarities)

# Get the similarity score of the most similar sentence
most_similar_score = similarities[most_similar_index]

# Print the results
print(f"Query: {query}")
print(f"Most similar document: {sentence_embeddings[most_similar_index]}")


Query: Encoder and Decoder stacks
Most similar document: [[ 1.00838579e-02 -2.19193071e-01 -7.17677772e-02  2.72334535e-02
   1.34210333e-01 -1.85139835e-01 -3.06049585e-01  3.58722880e-02
   4.41343039e-01 -1.85793787e-01  1.54395625e-01 -6.33859187e-02
   5.25927320e-02 -3.74090970e-02  1.00735746e-01 -2.72713006e-01
   2.12172672e-01  2.47396007e-01 -3.55664760e-01 -3.32987040e-01
   2.31802836e-01 -8.36551785e-02  2.56811202e-01  1.61790952e-01
   3.12705725e-01  5.55393212e-02 -2.79781997e-01 -1.93729520e-01
   1.32681668e-01 -1.49239242e-01 -3.57315332e-01  4.23969403e-02
  -1.29493445e-01  2.02298418e-01 -9.60447639e-02  3.27083319e-01
  -1.16327040e-01 -2.39065085e-02  3.21488678e-02 -1.26362428e-01
  -1.58474781e-02  1.16194509e-01  1.35354906e-01 -6.78390339e-02
   4.27989513e-01 -5.01910970e-02  4.35175578e-04 -8.59414041e-02
   1.01808041e-01 -1.60400961e-02 -6.44134998e-01 -4.33852673e-02
  -2.00075179e-01  3.39126065e-02  6.34828731e-02  1.93532124e-01
  -2.05294434e-02  

In [29]:
# print the releated text
print(sentences[most_similar_index])

Experiments on two machine translation tasks show these models to
be superior in quality while being more parallelizable and requiring significantly
less time to train
